import { Link } from 'react-router-dom';

const emergencyContacts = [
  { number: '105', name: 'Policía Nacional', description: 'Emergencias de seguridad', tone: 'police', symbol: 'shield' },
  { number: '116', name: 'Bomberos', description: 'Incendios y rescates', tone: 'fire', symbol: 'flame' },
  { number: '106', name: 'SAMU', description: 'Urgencias y emergencias médicas', tone: 'medical', symbol: 'cross' },
  { number: '100', name: 'Línea 100', description: 'Orientación ante violencia familiar y contra las mujeres', tone: 'support', symbol: 'heart' },
];

function ContactIcon({ type }) {
  const paths = { shield: 'M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6l-8-3Z', flame: 'M12 3c2 5 7 7 7 12a7 7 0 0 1-14 0c0-3 2-6 4-8 0 4 3 4 3-4Z', cross: 'M9 3h6v6h6v6h-6v6H9v-6H3V9h6V3Z', heart: 'M20 5c-3-3-7 0-8 2-1-2-5-5-8-2-5 5 8 15 8 15S25 10 20 5Z' };
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinejoin="round" aria-hidden="true"><path d={paths[type]} /></svg>;
}

export default function Welcome() {
  return <div className="welcome-page">
    <header className="welcome-header"><Link className="welcome-brand" to="/" aria-label="Gestión de incidencias: inicio"><img src="/logo.png" alt="" /><span>Gestión de incidencias<small>Conectamos comunidad e instituciones</small></span></Link><nav aria-label="Presentación"><a href="#como-funciona">Cómo funciona</a><Link className="button primary" to="/login">Iniciar sesión →</Link></nav></header>
    <main>
      <section className="welcome-hero" aria-labelledby="welcome-title"><div className="welcome-copy"><span className="welcome-tag">COMUNIDAD CONECTADA · PILOTO AYACUCHO</span><h1 id="welcome-title">Más cerca.<br />Mejor coordinados.<br /><em>Juntos por tu comunidad.</em></h1><p>Un espacio para comunicar lo que sucede y ayudar a las instituciones a organizar la atención. Información clara, reportes con ubicación y seguimiento en un solo lugar.</p><div className="welcome-actions"><Link className="button primary" to="/login">Entrar al panel institucional →</Link><a className="button ghost" href="#como-funciona">Conocer la plataforma</a></div><small>¿Eres ciudadano? Reporta y consulta tus casos desde nuestra app Android.</small><div className="welcome-partners"><span>Municipalidad</span><span>PNP</span><span>SAMU</span><span>Bomberos</span></div></div><figure className="welcome-art"><img src="/community-hero.png" alt="Ilustración de una ciudadana y equipos médicos, de bomberos y municipales colaborando en una plaza de Ayacucho" fetchPriority="high" width="1536" height="1024" /><figcaption><span aria-hidden="true">✦</span> La colaboración empieza con información clara.</figcaption></figure></section>
      <section className="welcome-emergencies" aria-labelledby="emergency-title"><div className="emergency-heading"><div><span className="eyebrow">Contactos oficiales · Perú</span><h2 id="emergency-title">Si necesitas ayuda, ten estos números a mano.</h2></div><span className="emergency-badge">No necesitas iniciar sesión</span></div><p>Ante una emergencia real, comunícate directamente con el servicio correspondiente. Esta plataforma de prueba no despacha ayuda.</p><div className="emergency-grid">{emergencyContacts.map(contact => <a key={contact.number} href={`tel:${contact.number}`} className={`emergency-card ${contact.tone}`} aria-label={`Llamar al ${contact.number}, ${contact.name}`}><span className="emergency-icon"><ContactIcon type={contact.symbol} /></span><strong className="emergency-number">{contact.number}</strong><h3>{contact.name}</h3><p>{contact.description}</p><span className="emergency-call">Llamar al {contact.number} <span aria-hidden="true">↗</span></span></a>)}</div><div className="emergency-sources"><span>Referencias: <a href="https://www.gob.pe/547-telefonos-de-emergencia" target="_blank" rel="noopener noreferrer">Teléfonos de emergencia · Gob.pe ↗</a> · <a href="https://www.gob.pe/44181-solicitar-ayuda-en-casos-de-violencia-contra-las-mujeres-e-integrantes-del-grupo-familiar-l-nea-100" target="_blank" rel="noopener noreferrer">Línea 100 · Gob.pe ↗</a></span><span>Serenazgo: el número depende de tu municipalidad.</span></div></section>
      <section className="welcome-how" id="como-funciona" aria-labelledby="how-title"><span className="eyebrow">Sencillo, de principio a fin</span><h2 id="how-title">¿Cómo funciona?</h2><div className="welcome-steps"><article><span className="step-number">01</span><h3>Comunica lo que sucede</h3><p>Desde Android, describe el caso, señala el lugar y adjunta una foto si ayuda a entenderlo.</p></article><article><span className="step-number">02</span><h3>Coordina la atención</h3><p>La institución autorizada revisa el reporte y organiza sus unidades y personal desde el panel.</p></article><article><span className="step-number">03</span><h3>Consulta el seguimiento</h3><p>Revisa los cambios de estado de tus reportes y los avisos disponibles en la aplicación.</p></article></div></section>
      <section className="welcome-access"><div><h2>¿Formas parte de una institución?</h2><p>Ingresa con tu cuenta autorizada para revisar los reportes de tu ámbito.</p></div><Link className="button primary" to="/login">Iniciar sesión →</Link></section>
    </main><footer className="welcome-footer"><strong>Piloto de demostración · Ayacucho</strong><p>Esta plataforma utiliza datos de prueba y no sustituye los canales oficiales de emergencia.</p></footer>
  </div>;
}
